# Generated by Django 5.1.2 on 2025-10-25 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFlowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('flow_data', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_flow_config',
            },
        ),
        migrations.AlterField(
            model_name='usercomicprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('current_step', models.CharField(default='intro', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='api.user')),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Message'), ('system', 'System Message')], max_length=10)),
                ('character', models.CharField(blank=True, max_length=50, null=True)),
                ('message_text', models.TextField()),
                ('step_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_id', models.CharField(default='intro', max_length=50)),
                ('sequence_order', models.IntegerField(default=0)),
                ('message_data', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['timestamp', 'sequence_order'],
                'indexes': [models.Index(fields=['session', 'activity_id'], name='chat_messag_session_aae6b4_idx'), models.Index(fields=['session', 'sequence_order'], name='chat_messag_session_ba2e32_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('started', 'Started'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_progress', to='api.chatsession')),
            ],
            options={
                'db_table': 'activity_progress',
                'ordering': ['activity_id'],
                'unique_together': {('session', 'activity_id')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('storage_key', models.CharField(max_length=100)),
                ('answer_text', models.TextField()),
                ('answer_type', models.CharField(choices=[('essay', 'Essay'), ('discussion', 'Discussion'), ('challenge', 'Challenge'), ('creative', 'Creative'), ('reflective', 'Reflective')], max_length=20)),
                ('question_text', models.TextField()),
                ('step_id', models.CharField(max_length=50)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_id', models.CharField(max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.chatsession')),
            ],
            options={
                'db_table': 'user_answers',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'activity_id'], name='user_answer_session_f9f037_idx')],
                'unique_together': {('session', 'question_id')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_kegiatan', models.CharField(default='kimia_hijau', max_length=50)),
                ('total_answers', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.user')),
            ],
            options={
                'db_table': 'user_progress',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'session')},
            },
        ),
    ]
